# Generated by Django

from django.db import migrations

def create_initial_plans(apps, schema_editor):
    """
    Cria os planos iniciais do sistema.
    """
    Plano = apps.get_model('accounts', 'Plano')
    
    planos = [
        {'nome': 'economico', 'preco_mensal': 19.99},
        {'nome': 'padrao', 'preco_mensal': 29.99},
        {'nome': 'avancado', 'preco_mensal': 49.99},
    ]

    for plano_data in planos:
        # Cria o plano apenas se ele não existir
        Plano.objects.get_or_create(nome=plano_data['nome'], defaults={'preco_mensal': plano_data['preco_mensal']})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pagamento'), 
    ]

    operations = [
        migrations.RunPython(create_initial_plans),
    ]