# Generated by Django 5.0.6 on 2025-10-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_bairro_empresa_cep_empresa_cidade_and_more'),
        ('accounts', '0002_userpreference'),
    ]

    operations = [
    ]
