# Generated by Django 5.0.6 on 2025-11-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='cartao_bandeira',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cartao_final',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cartao_validade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='metodo_pagamento_padrao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
