# docker-compose.yml

# Default: SQLite (no env required).
# Optional Cloud SQL: enable with `--profile cloudsql` and supply env vars.
services:
  web:
    build:
      context: .
    image: ezgestor-app:latest
    container_name: ezgestor-container
    ports:
      - "8000:8080"
    volumes:
      - db_data:/app/sqlite-data
    environment:
      # Default to a persistent SQLite file inside the volume-backed directory
      DATABASE_URL: ${DATABASE_URL:-sqlite:////app/sqlite-data/db.sqlite3}
      CONN_MAX_AGE: ${CONN_MAX_AGE:-0}

  migrate:
    build:
      context: .
    image: ezgestor-app:latest
    command: ["python", "manage.py", "migrate"]
    environment:
      # Match the web default so migrations hit the same DB by default
      DATABASE_URL: ${DATABASE_URL:-sqlite:////app/sqlite-data/db.sqlite3}
      CONN_MAX_AGE: ${CONN_MAX_AGE:-0}
    volumes:
      - db_data:/app/sqlite-data
    restart: "no"

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    command:
      - "${CLOUD_SQL_CONNECTION_NAME}"
      - "--address=0.0.0.0"
      - "--port=3306"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/sa.json
    volumes:
      - ./secrets:/secrets:ro
    # No host port mapping needed; web connects to host cloudsql-proxy:3306 on the Docker network

volumes:
  db_data: