# docker-compose.yml

# Defines the services (containers) for your application.
services:
  # We'll name our service 'web'.
  web:
    # Instructions for how to build the image.
    build:
      # Use the Dockerfile in the current directory ('.').
      context: .
    # Name the image that will be built.
    image: ezgestor-app:latest
    # Give the running container a consistent name.
    container_name: ezgestor-container
    # Map port 8000 on your local machine to port 8080 inside the container.
    # Your Dockerfile exposes 8080, so we connect to that.
    ports:
      - "8000:8080"
    # Mount a volume to persist the database file.
    volumes:
      - db_data:/app/db.sqlite3

# Defines the named volumes that can be used by services.
volumes:
  # This creates a managed volume named 'db_data' for our database.
  db_data: