"""
Django settings for ezgestor_api project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
# Use the environment variable if it exists, otherwise fall back to the insecure key for development.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-)+(t*2!@+(+)xams#bo-ophq4u%zrmh4(54#bb15uwt3j9y0ef'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Use the environment variable for DEBUG, defaulting to True for local development.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'marcos.freire@mail.uft.edu.br'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'EzGestor <marcos.freire@mail.uft.edu.br>'

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

# Permite hosts de rede privada (importante para mobile)
ALLOWED_HOSTS.extend(['10.0.2.2', 'localhost', '127.0.0.1', '::1', '192.168.10.104'])

# Em desenvolvimento, permita qualquer host para facilitar testes em rede local/LAN
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8081,http://127.0.0.1:8081').split(',')
    if o.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'handler',
    'estoque',
    'vendas',
    'financeiro',
    'reports',
    'logs',
    'rest_framework_simplejwt',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Deve estar no topo
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ezgestor_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ezgestor_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Prefer DATABASE_URL when provided (e.g., mysql://user:pass@host:port/dbname?charset=utf8mb4)
CONN_MAX_AGE = int(os.environ.get('CONN_MAX_AGE', '0') or '0')
database_url = os.environ.get('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.parse(
        database_url,
        conn_max_age=CONN_MAX_AGE,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL should end with a slash and is used by the SPA assets
STATIC_URL = os.environ.get('STATIC_URL', '/static/')

# Where collectstatic puts files (used in production)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Include the built frontend during development or when present
# This allows manage.py collectstatic to pick up the Vite dist
FRONTEND_DIST = os.environ.get('FRONTEND_DIST', str(Path(BASE_DIR).parent / 'frontend' / 'dist'))
if os.path.isdir(FRONTEND_DIST):
    STATICFILES_DIRS = [FRONTEND_DIST]

# Use WhiteNoise compressed manifest storage in production; fall back in dev
STATICFILES_STORAGE = os.environ.get(
    'STATICFILES_STORAGE',
    'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Disable DRF's ?format=... override so we can use 'format' as a regular query param
    'URL_FORMAT_OVERRIDE': None,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # Duração do token de acesso
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),   # Duração do token de atualização
}

# CORS Configuration
def _env_flag(name: str, default: str = 'False') -> bool:
    return os.environ.get(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}

# Configuração principal do CORS
# Para desenvolvimento, permita todas as origens da rede local
CORS_ALLOW_ALL_ORIGINS = _env_flag('CORS_ALLOW_ALL_ORIGINS', 'true') 

# Se não for permitir todas as origens, use a lista específica
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8081",
        "http://127.0.0.1:8081",
    ]
else:
    CORS_ALLOWED_ORIGINS = []

# Headers e métodos permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_CREDENTIALS = True

# Adicione também estas configurações para maior compatibilidade
CORS_ALLOW_PRIVATE_NETWORK = True  # Importante para desenvolvimento local

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.Usuario'

# Media files (uploaded product images) with unified cloud/local switch
# Default to local mode (no .env required)
USE_CLOUD_BACKENDS = _env_flag('USE_CLOUD_BACKENDS', 'False')

def _is_set_env(name: str) -> bool:
    value = os.environ.get(name)
    return bool(value and value.strip())

# Validate required env set for cloud mode before configuring storage
if USE_CLOUD_BACKENDS:
    missing = []
    if not _is_set_env('GS_BUCKET_NAME'):
        missing.append('GS_BUCKET_NAME')
    if not _is_set_env('DATABASE_URL'):
        missing.append('DATABASE_URL')
    if not _is_set_env('CLOUD_SQL_CONNECTION_NAME'):
        missing.append('CLOUD_SQL_CONNECTION_NAME')
    if missing:
        raise ImproperlyConfigured(
            f"USE_CLOUD_BACKENDS=True requires these env vars: {', '.join(missing)}."
        )

# Media backend follows the unified switch
USE_GCS_MEDIA = USE_CLOUD_BACKENDS

if USE_GCS_MEDIA:
    # Use Google Cloud Storage for media
    INSTALLED_APPS.append('storages')
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    GS_BUCKET_NAME = os.environ['GS_BUCKET_NAME']
    GS_QUERYSTRING_AUTH = False  # public URLs
    GS_DEFAULT_ACL = None        # uniform bucket-level access
    # Compose the media base URL from the bucket name (stable host)
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
else:
    # Legacy local filesystem media
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Enforce coupling between database and media backends to avoid mixed setups
_db_engine = DATABASES['default']['ENGINE']
_is_sqlite = _db_engine.endswith('sqlite3')
_is_cloud_db = not _is_sqlite

if USE_CLOUD_BACKENDS:
    if _is_sqlite:
        raise ImproperlyConfigured('USE_CLOUD_BACKENDS=True requires non-sqlite DATABASE_URL (Cloud SQL).')
else:
    # Offline/local mode must not use cloud DB or cloud-only identifiers
    if _is_cloud_db:
        raise ImproperlyConfigured('USE_CLOUD_BACKENDS=False requires SQLite database.')
    # Treat empty string as unset to align with docker-compose defaults
    if _is_set_env('GS_BUCKET_NAME') or _is_set_env('CLOUD_SQL_CONNECTION_NAME'):
        raise ImproperlyConfigured(
            'USE_CLOUD_BACKENDS=False requires GS_BUCKET_NAME and CLOUD_SQL_CONNECTION_NAME to be unset.'
        )