# Generated by Django 5.0.6 on 2025-09-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_do_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_estoque', models.IntegerField()),
                ('quantidade_minima_estoque', models.IntegerField(default=0, help_text='Quantidade mínima para alerta de baixo estoque.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='accounts.empresa')),
            ],
        ),
    ]
