# Generated by Django 5.0.6 on 2025-09-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('empresa', 'codigo_do_produto')},
        ),
    ]
