# Generated by Django 5.0.6 on 2025-10-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('estoque', '0002_alter_produto_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='produto_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo_do_produto'], name='produto_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'codigo_do_produto'], name='empresa_codigo_comp_idx'),
        ),
    ]
