# Generated by Django 5.0.6 on 2025-10-06 14:56

import estoque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=estoque.models.produto_image_upload_to),
        ),
    ]
