# Generated by Django 5.0.6 on 2025-10-30 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('action_type', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Deleção'), ('LOGIN', 'Login')], max_length=10, verbose_name='Ação')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Afetado')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Ação',
                'verbose_name_plural': 'Logs de Ações',
                'ordering': ['-action_time'],
            },
        ),
    ]
