# Generated by Django 5.0.6 on 2025-10-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Deleção'), ('SOFT_DELETE', 'Desativação'), ('LOGIN', 'Login')], max_length=15, verbose_name='Ação'),
        ),
    ]
