# Generated by ChatGPT on 2025-10-04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente_nome',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_email',
            field=models.EmailField(max_length=254, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_telefone',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
    ]
